name: 'CI'

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          coverage: 'xdebug'
          php-version: '8.0'
      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction --no-progress
      - name: PHPUnit
        id: coverage
        run: >
          composer run phpunit

  static_analysis:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          coverage: 'none'
          php-version: '8.0'
      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction --no-progress
      - name: Check style
        run: composer run check-style
      - name: phpstan
        run: composer run phpstan